# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: cpm
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    package_name: cpm
    vendor: COZ Inc.
    homepage: https://github.com/CityOfZion/
    maintainer: COZ
    description: |-
      NEO Contract Package Manager
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
#chocolateys:
#  -
#    project_url: https://github.com/CityOfZion/cpm
#    copyright: 2022 COZ Inc
#    license_url: https://github.com/CityOfZion/cpm/blob/master/LICENSE
#    require_license_acceptance: false
#    project_source_url: https://github.com/CityOfZion/cpm
#    docs_url: https://github.com/CityOfZion/cpm/blob/main/README.md
#    bug_tracker_url: https://github.com/CityOfZion/cpm/issues
#    summary: NEO Blockchain Contract Package Manager
#
#    description: |
#      {{ .ProjectName }} installer package.
#      Download selected contracts from a chain to your local chain for development purposes.
#      Generate SDKs for selected contracts to work with.
#
#    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
#    source_repo: "https://push.chocolatey.org/"
#
#    # Setting this will prevent goreleaser to actually try to push the package
#    # to chocolatey repository, leaving the responsability of publishing it to
#    # the user.
#    skip_publish: false

# Github release
release:
  draft: true
  replace_existing_draft: true

# OSX homebrew tap
brews:
  -
    tap:
      owner: CityOfZion
      name: homebrew-tap
    homepage: https://github.com/CityOfZion/cpm
    description: NEO Blockchain Contract Package Manager
    skip_upload: false